### ISSUE TITLE
Allow choosing the Vert.x dependencies to be added to a new Vert.x project type

### ISSUE THREAD

**Issue by gastaldi** [cescoffier/vertx-forge-addon#10]
It would be interesting if the Vert.x ProjectType setup could provide the option to choose the dependencies to be added, similar to what's done in https://github.com/forge/wildfly-swarm-addon/blob/master/src/main/java/org/jboss/forge/addon/swarm/ui/AddFractionCommand.java

**Comment by cescoffier** [comment]
+1

Working on it.
